<?php
return
    [
        'GDPR_DATAMAP' =>
            [
                'customers' => [
                    'firstname',
                    'lastname',
                    'loginname',
                    'email',
                    'telephone',
                    'fax',
                    'sms',
                    'cart',
                    'wishlist',
                    'ip',
                    'data',
                    'last_login',
                ],
                'addresses' => [
                    'company',
                    'firstname',
                    'lastname',
                    'address_1',
                    'address_2',
                    'postcode',
                    'city',
//                    'country_id',
//                    'zone_id',
                ],
                'orders'    => [
                    'firstname',
                    'lastname',
                    'telephone',
                    'fax',
                    'email',
                    'shipping_firstname',
                    'shipping_lastname',
                    'shipping_company',
                    'shipping_address_1',
                    'shipping_address_2',
                    'shipping_city',
                    'shipping_postcode',
                    'shipping_zone',
                    'shipping_zone_id',
                    'shipping_country',
                    'shipping_country_id',
                    'payment_firstname',
                    'payment_lastname',
                    'payment_company',
                    'payment_address_1',
                    'payment_address_2',
                    'payment_city',
                    'payment_postcode',
                    'payment_zone',
                    'payment_zone_id',
                    'payment_country',
                    'payment_country_id',
                    'ip',
                ],
            ],
    ];
