ALTER TABLE `ac_addresses` ENGINE=INNODB;
ALTER TABLE `ac_categories` ENGINE=INNODB;
ALTER TABLE `ac_category_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_categories_to_stores` ENGINE=INNODB;
ALTER TABLE `ac_countries` ENGINE=INNODB;
ALTER TABLE `ac_country_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_coupons` ENGINE=INNODB;
ALTER TABLE `ac_coupon_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_coupons_products` ENGINE=INNODB;
ALTER TABLE `ac_currencies` ENGINE=INNODB;
ALTER TABLE `ac_customers` ENGINE=INNODB;
ALTER TABLE `ac_customer_groups` ENGINE=INNODB;
ALTER TABLE `ac_customer_transactions` ENGINE=INNODB;
ALTER TABLE `ac_online_customers` ENGINE=INNODB;
ALTER TABLE `ac_downloads` ENGINE=INNODB;
ALTER TABLE `ac_download_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_download_attribute_values` ENGINE=INNODB;
ALTER TABLE `ac_extensions` ENGINE=INNODB;
ALTER TABLE `ac_banners` ENGINE=INNODB;
ALTER TABLE `ac_banner_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_banner_stat` ENGINE=INNODB;
ALTER TABLE `ac_locations` ENGINE=INNODB;
ALTER TABLE `ac_languages` ENGINE=INNODB;
ALTER TABLE `ac_language_definitions` ENGINE=INNODB;
ALTER TABLE `ac_length_classes` ENGINE=INNODB;
ALTER TABLE `ac_length_class_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_manufacturers` ENGINE=INNODB;
ALTER TABLE `ac_manufacturers_to_stores` ENGINE=INNODB;
ALTER TABLE `ac_orders` ENGINE=INNODB;
ALTER TABLE `ac_order_downloads` ENGINE=INNODB;
ALTER TABLE `ac_order_downloads_history` ENGINE=INNODB;
ALTER TABLE `ac_order_data` ENGINE=INNODB;
ALTER TABLE `ac_order_data_types` ENGINE=INNODB;
ALTER TABLE `ac_order_history` ENGINE=INNODB;
ALTER TABLE `ac_order_options` ENGINE=INNODB;
ALTER TABLE `ac_order_products` ENGINE=INNODB;
ALTER TABLE `ac_order_statuses` ENGINE=INNODB;
ALTER TABLE `ac_order_status_ids` ENGINE=INNODB;
ALTER TABLE `ac_order_totals` ENGINE=INNODB;
ALTER TABLE `ac_products` ENGINE=INNODB;
ALTER TABLE `ac_product_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_product_discounts` ENGINE=INNODB;
ALTER TABLE `ac_products_featured` ENGINE=INNODB;
ALTER TABLE `ac_product_options` ENGINE=INNODB;
ALTER TABLE `ac_product_option_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_product_option_values` ENGINE=INNODB;
ALTER TABLE `ac_product_option_value_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_products_related` ENGINE=INNODB;
ALTER TABLE `ac_product_specials` ENGINE=INNODB;
ALTER TABLE `ac_product_tags` ENGINE=INNODB;
ALTER TABLE `ac_products_to_categories` ENGINE=INNODB;
ALTER TABLE `ac_products_to_downloads` ENGINE=INNODB;
ALTER TABLE `ac_products_to_stores` ENGINE=INNODB;
ALTER TABLE `ac_reviews` ENGINE=INNODB;
ALTER TABLE `ac_settings` ENGINE=INNODB;
ALTER TABLE `ac_stock_statuses` ENGINE=INNODB;
ALTER TABLE `ac_stores` ENGINE=INNODB;
ALTER TABLE `ac_store_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_tax_classes` ENGINE=INNODB;
ALTER TABLE `ac_tax_class_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_tax_rates` ENGINE=INNODB;
ALTER TABLE `ac_tax_rate_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_url_aliases` ENGINE=INNODB;
ALTER TABLE `ac_users` ENGINE=INNODB;
ALTER TABLE `ac_user_groups` ENGINE=INNODB;
ALTER TABLE `ac_user_notifications` ENGINE=INNODB;
ALTER TABLE `ac_customer_notifications` ENGINE=INNODB;
ALTER TABLE `ac_weight_classes` ENGINE=INNODB;
ALTER TABLE `ac_weight_class_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_zones` ENGINE=INNODB;
ALTER TABLE `ac_zone_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_zones_to_locations` ENGINE=INNODB;
ALTER TABLE `ac_pages` ENGINE=INNODB;
ALTER TABLE `ac_page_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_contents` ENGINE=INNODB;
ALTER TABLE `ac_content_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_contents_to_stores` ENGINE=INNODB;
ALTER TABLE `ac_blocks` ENGINE=INNODB;
ALTER TABLE `ac_custom_blocks` ENGINE=INNODB;
ALTER TABLE `ac_custom_lists` ENGINE=INNODB;
ALTER TABLE `ac_block_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_block_templates` ENGINE=INNODB;
ALTER TABLE `ac_layouts` ENGINE=INNODB;
ALTER TABLE `ac_pages_layouts` ENGINE=INNODB;
ALTER TABLE `ac_block_layouts` ENGINE=INNODB;
ALTER TABLE `ac_pages_forms` ENGINE=INNODB;
ALTER TABLE `ac_forms` ENGINE=INNODB;
ALTER TABLE `ac_form_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_fields` ENGINE=INNODB;
ALTER TABLE `ac_field_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_field_values` ENGINE=INNODB;
ALTER TABLE `ac_form_groups` ENGINE=INNODB;
ALTER TABLE `ac_fields_groups` ENGINE=INNODB;
ALTER TABLE `ac_fields_group_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_messages` ENGINE=INNODB;
ALTER TABLE `ac_ant_messages` ENGINE=INNODB;
ALTER TABLE `ac_datasets` ENGINE=INNODB;
ALTER TABLE `ac_dataset_properties` ENGINE=INNODB;
ALTER TABLE `ac_dataset_definition` ENGINE=INNODB;
ALTER TABLE `ac_dataset_column_properties` ENGINE=INNODB;
ALTER TABLE `ac_dataset_values` ENGINE=INNODB;
ALTER TABLE `ac_resource_library` ENGINE=INNODB;
ALTER TABLE `ac_resource_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_resource_types` ENGINE=INNODB;
ALTER TABLE `ac_resource_map` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_values` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_value_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_groups` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_groups_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_types` ENGINE=INNODB;
ALTER TABLE `ac_global_attributes_type_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_product_filters` ENGINE=INNODB;
ALTER TABLE `ac_product_filter_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_product_filter_ranges` ENGINE=INNODB;
ALTER TABLE `ac_product_filter_ranges_descriptions` ENGINE=INNODB;
ALTER TABLE `ac_extension_dependencies` ENGINE=INNODB;
ALTER TABLE `ac_encryption_keys` ENGINE=INNODB;
ALTER TABLE `ac_tasks` ENGINE=INNODB;
ALTER TABLE `ac_task_details` ENGINE=INNODB;
ALTER TABLE `ac_task_steps` ENGINE=INNODB;

ALTER TABLE `ac_language_definitions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_customers` ADD FOREIGN KEY (`store_id`) REFERENCES `ac_stores`(`store_id`);
ALTER TABLE `ac_country_descriptions` ADD FOREIGN KEY (`country_id`) REFERENCES `ac_countries`(`country_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_country_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_zones` ADD FOREIGN KEY (`country_id`) REFERENCES `ac_countries`(`country_id`);
ALTER TABLE `ac_zone_descriptions` ADD FOREIGN KEY (`zone_id`) REFERENCES `ac_zones`(`zone_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_zone_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_zones_to_locations` ADD FOREIGN KEY (`zone_id`) REFERENCES `ac_zones`(`zone_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_zones_to_locations` ADD FOREIGN KEY (`country_id`) REFERENCES `ac_countries`(`country_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_zones_to_locations` ADD FOREIGN KEY (`location_id`) REFERENCES `ac_locations`(`location_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_addresses` ADD FOREIGN KEY (`customer_id`) REFERENCES `ac_customers`(`customer_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_addresses` ADD FOREIGN KEY (`country_id`) REFERENCES `ac_countries`(`country_id`);
ALTER TABLE `ac_addresses` ADD FOREIGN KEY (`zone_id`) REFERENCES `ac_zones`(`zone_id`);

ALTER TABLE `ac_categories` CHANGE COLUMN `parent_id` `parent_id` int(11) DEFAULT NULL;
UPDATE `ac_categories` SET `parent_id` = NULL WHERE `parent_id` = 0;
ALTER TABLE `ac_categories` ADD FOREIGN KEY (`parent_id`) REFERENCES `ac_categories`(`category_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_category_descriptions` ADD FOREIGN KEY (`category_id`) REFERENCES `ac_categories`(`category_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_category_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_categories_to_stores` ADD FOREIGN KEY (`category_id`) REFERENCES `ac_categories`(`category_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_categories_to_stores` ADD FOREIGN KEY (`store_id`) REFERENCES `ac_stores`(`store_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ac_coupon_descriptions` ADD FOREIGN KEY (`coupon_id`) REFERENCES `ac_coupons`(`coupon_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_coupon_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);

ALTER TABLE `ac_coupons_products` ADD FOREIGN KEY (`coupon_id`) REFERENCES `ac_coupons`(`coupon_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_coupons_products` ADD FOREIGN KEY (`product_id`) REFERENCES `ac_products`(`product_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ac_download_descriptions` ADD FOREIGN KEY (`download_id`) REFERENCES `ac_downloads`(`download_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_download_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_download_attribute_values` ADD FOREIGN KEY (`download_id`) REFERENCES `ac_downloads`(`download_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ac_banner_descriptions` ADD FOREIGN KEY (`banner_id`) REFERENCES `ac_banners`(`banner_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_banner_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_banner_stat` ADD FOREIGN KEY (`banner_id`) REFERENCES `ac_banners`(`banner_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ac_length_class_descriptions` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);

ALTER TABLE `ac_manufacturers_to_stores` ADD FOREIGN KEY (`manufacturer_id`) REFERENCES `ac_manufacturers`(`manufacturer_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ac_manufacturers_to_stores` ADD FOREIGN KEY (`store_id`) REFERENCES `ac_stores`(`store_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `ac_orders` ADD FOREIGN KEY (`store_id`) REFERENCES `ac_stores`(`store_id`);
ALTER TABLE `ac_orders` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);
ALTER TABLE `ac_orders` ADD FOREIGN KEY (`currency_id`) REFERENCES `ac_currencies`(`currency_id`);
ALTER TABLE `ac_orders` CHANGE COLUMN `customer_id` `customer_id` int(11) DEFAULT NULL;
UPDATE `ac_orders` SET `customer_id` = NULL WHERE `customer_id` = 0;
ALTER TABLE `ac_orders` ADD FOREIGN KEY (`customer_id`) REFERENCES `ac_customers`(`customer_id`) ON DELETE SET NULL;
--????? Will not create relationship if IDs are not present in customer's table.
ALTER TABLE `ac_orders` CHANGE COLUMN `coupon_id` `coupon_id` int(11) DEFAULT NULL;
UPDATE `ac_orders` SET `coupon_id` = NULL WHERE `coupon_id` = 0;
ALTER TABLE `ac_orders` ADD FOREIGN KEY (`coupon_id`) REFERENCES `ac_coupons`(`coupon_id`) ON DELETE SET NULL;

ALTER TABLE `ac_customer_transactions` ADD FOREIGN KEY  (`customer_id`) REFERENCES `ac_customers`(`customer_id`);
ALTER TABLE `ac_customer_transactions` ADD FOREIGN KEY (`order_id`) REFERENCES `ac_orders`(`order_id`);

ALTER TABLE `ac_order_products` ADD FOREIGN KEY (`order_id`) REFERENCES `ac_orders`(`order_id`);
ALTER TABLE `ac_order_products` ADD FOREIGN KEY (`product_id`) REFERENCES `ac_products`(`product_id`);

ALTER TABLE `ac_order_downloads` ADD FOREIGN KEY (`download_id`) REFERENCES `ac_downloads`(`download_id`);
ALTER TABLE `ac_order_downloads` ADD FOREIGN KEY (`order_id`) REFERENCES `ac_orders`(`order_id`);
ALTER TABLE `ac_order_downloads` ADD FOREIGN KEY (`order_product_id`) REFERENCES `ac_order_products`(`order_product_id`);

ALTER TABLE `ac_order_downloads_history` ADD FOREIGN KEY (`order_download_id`) REFERENCES `ac_order_downloads`(`order_download_id`);
ALTER TABLE `ac_order_downloads_history` ADD FOREIGN KEY (`download_id`) REFERENCES `ac_downloads`(`download_id`);
ALTER TABLE `ac_order_downloads_history` ADD FOREIGN KEY (`order_id`) REFERENCES `ac_orders`(`order_id`);
ALTER TABLE `ac_order_downloads_history` ADD FOREIGN KEY (`order_product_id`) REFERENCES `ac_order_products`(`order_product_id`);

ALTER TABLE `ac_order_data` ADD FOREIGN KEY (`order_id`) REFERENCES `ac_orders`(`order_id`);
ALTER TABLE `ac_order_data` ADD FOREIGN KEY (`type_id`) REFERENCES `ac_order_data_types`(`type_id`);
ALTER TABLE `ac_order_data_types` ADD FOREIGN KEY (`language_id`) REFERENCES `ac_languages`(`language_id`);

